name: Create Release Branch

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  create-release-branch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get default branch
        run: echo "DEFAULT_BRANCH=${{ github.event.repository.default_branch }}" >> $GITHUB_ENV

      - name: Get release tag
        run: echo "RELEASE_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Create release branch
        run: |
          BRANCH_NAME="release/${GITHUB_REPOSITORY#*/}-${RELEASE_TAG}"

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git checkout $DEFAULT_BRANCH
          git pull origin $DEFAULT_BRANCH

          git checkout -b "$BRANCH_NAME"
          git push origin "$BRANCH_NAME"